#
# Travis CI configuration file for DSFML
#
language: d
dist: bionic
git:
  depth: 3

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libjpeg8-dev
      - libopenal-dev
      - libpthread-stubs0-dev
      - libsndfile1-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - libxcb-image0-dev
      - libxcb-randr0-dev
      - libudev-dev
      - libvorbis-dev
      - libflac-dev


os:
  - linux
  - osx

d:
  - dmd
  #-gdc
  - ldc

jobs:
  exclude:
    - os: osx
      d: gdc

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then INSTALL_PREFIX=/usr; fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then INSTALL_PREFIX=/usr/local; fi

# Download and install SFML and CSFML
install:
  - git submodule update --init --recursive
  - cd SFML
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX .
  - make
  - sudo make install
  - cd ../CSFML
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX .
  - make
  - sudo make install
  - cd ..

script:
  - dub build --arch=x86_64
  - dub build --arch=x86
