#
# Travis CI configuration file for DSFML
# https://config.travis-ci.com/explore
#
language: d
git:
  depth: 3
notifications:
  email: false

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libjpeg8-dev
      - libopenal-dev
      - libpthread-stubs0-dev
      - libsndfile1-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - libxcb-image0-dev
      - libxcb-randr0-dev
      - libudev-dev
      - libvorbis-dev
      - libflac-dev

jobs:
  include:
    - name: Linux DMD
      os: linux
      d: dmd
      env:
        - INSTALL_PREFIX="/usr"

    - name: Linux LDC
      os: linux
      d: ldc
      env:
        - INSTALL_PREFIX="/usr"

    - name: MacOS DMD
      os: osx
      d: dmd
      env:
        - INSTALL_PREFIX="/usr/local"

    - name: MacOS LDC
      os: osx
      d: ldc
      env:
        - INSTALL_PREFIX="/usr/local"

# Download and install SFML and CSFML
install:
  - git submodule update --init --recursive
  - cd SFML
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX .
  - make
  - sudo make install
  - cd ../CSFML
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX .
  - make
  - sudo make install
  - cd ..

script:
  - dub build --arch=x86_64
  - dub build --arch=x86
